kind: pipeline
type: docker
name: Drone


clone:
  disable: true


steps:
  - name: 代码
    image: dronestock/git

  - name: 编译
    image: pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      output: changelog
      compress:
        enabled: false

  - name: 日志
    image: dronestock/changelog
    commands:
      - echo $DRONE_NETRC_USERNAME
    when:
      branch:
        - master


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
