kind: pipeline
type: docker
name: Drone


clone:
  disable: true


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      output: changelog
      compress:
        enabled: false


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
